// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Main: typeof import('./src/components/Main.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    PopAlert: typeof import('./src/components/PopAlert.vue')['default']
    PopSave: typeof import('./src/components/PopSave.vue')['default']
    PopShare: typeof import('./src/components/PopShare.vue')['default']
    PopWindow: typeof import('./src/components/PopWindow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
  }
}
